### ISSUE TITLE
To complete the holl game and have all the items and lvl 99.9999999

### ISSUE THREAD

**Issue by savage8685** [CRobbins0867/ProdigyHacking--MobileHacking#12]
***What items should be in the account?***:

***What level do you want, how much gold, dark tower floor, etc?***:

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:

**Comment by CRobbins0867** [comment]
@savage8685 

user: COOL_THE_DUDE

pass: a12345

**Comment by savage8685** [comment]
How to change the password on it

**Comment by savage8685** [comment]
Can you go in the acc on get all the pets on it pls

**Comment by savage8685** [comment]
Can go in the acc and get all the pet in it pls

**Comment by CRobbins0867** [comment]
i cant that would take too long and about the pass i  wull not go on the account EVER

**Comment by savage8685** [comment]
You can get on it take as long as you want dude

**Comment by NameIsA** [comment]
> @savage8685
> 
> user: -
> 
> pass: -

I suggest you delete this reply now, so other people can't login to it.

**Comment by savage8685** [comment]
What is the user name and the password

**Comment by NameIsA** [comment]
https://github.com/CRobbins0867/ProdigyHacking--MobileHacking/issues/12#issuecomment-782423837 @savage8685
