### ISSUE TITLE
Get on the acc as long as you want pls get all the pets for dude pls

### ISSUE THREAD

**Issue by savage8685** [CRobbins0867/ProdigyHacking--MobileHacking#13]
***What items should be in the account?***:

***What level do you want, how much gold, dark tower floor, etc?***:

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:

**Comment by savage8685** [comment]
Respond pls

**Comment by CRobbins0867** [comment]
i gave you a account with everything and 2 of each epics so STOP please

**Comment by savage8685** [comment]
Ok thank you

**Comment by NameIsA** [comment]
I suggest you delete this issue, it's a duplicate.
