### ISSUE TITLE
I want acc with level 100 and have all the pets and the game completed 

### ISSUE THREAD

**Issue by savage8685** [CRobbins0867/ProdigyHacking--MobileHacking#17]
***What items should be in the account?***:

***What level do you want, how much gold, dark tower floor, etc?***:

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:

**Comment by savage8685** [comment]
Pls open it pls

**Comment by irhrhd** [comment]
Yes We can make this happen It will be just a little then youll have it okay!

**Comment by savage8685** [comment]
Ook

**Comment by savage8685** [comment]
Ok

**Comment by savage8685** [comment]
My email is s14936@hindsschools.com

**Comment by CRobbins0867** [comment]
@savage8685 you cant get all pets because if you equip a pet then your game would freeze when you go into battle but i cant give you epics and everything else? expect for membership, is that okay?

**Comment by savage8685** [comment]
Yeah that’s ok

**Comment by CRobbins0867** [comment]
user: hfjgfdg

pass: a12345

**Comment by irhrhd** [comment]
I had to email him the account so he has it now

**Comment by CRobbins0867** [comment]
@irhrhd i already gave him a account!

**Comment by irhrhd** [comment]
Okay xD

**Comment by savage8685** [comment]
Pls

**Comment by irhrhd** [comment]
Yes do you need something

**Comment by savage8685** [comment]
Nah

**Comment by NameIsA** [comment]
@CRobbins0867 https://github.com/CRobbins0867/ProdigyHacking--MobileHacking/issues/17#issuecomment-786083693 delete that reply to protect their security

**Comment by savage8685** [comment]
Hi how is your day going

**Comment by irhrhd** [comment]
Deleted
