### ISSUE TITLE
Can I get a acc with all the pets and all the other stuff and 567890m gold pls and all the epics

### ISSUE THREAD

**Issue by whythokid8675** [CRobbins0867/ProdigyHacking--MobileHacking#22]
***What items should be in the account?***:

***What level do you want, how much gold, dark tower floor, etc?***:

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:

**Comment by whythokid8675** [comment]
My email is s14936@hindsschools.com

**Comment by whythokid8675** [comment]
And lvl 1,000

**Comment by irhrhd** [comment]
Sure thing ill get started you can always do it your self you know just use this link
https://discord.gg/QusT2R3pnW

**Comment by whythokid8675** [comment]
Am on a school device so discord don’t work but thank you tho can you make the lvl on the acc 1,000 pls

**Comment by whythokid8675** [comment]
Are you done yet

**Comment by irhrhd** [comment]
Im waiting for my boss to tell me if i can or not

**Comment by whythokid8675** [comment]
Oh ok

**Comment by whythokid8675** [comment]
Have your boss responded yet

**Comment by whythokid8675** [comment]
Hello anything yet dude

**Comment by whythokid8675** [comment]
Hello respond

**Comment by CRobbins0867** [comment]
hey sorry what do you need?

**Comment by CRobbins0867** [comment]
@whythokid8675 

user: JADYEN_THE_WIZARDD

pass: 010101

**Comment by irhrhd** [comment]
Finally boss check the organization we haves chat please

**Comment by whythokid8675** [comment]
Thx

**Comment by whythokid8675** [comment]
I though I was getting a acc with a lvl 1,000 and all the pets?

**Comment by CRobbins0867** [comment]
sorry you cant get all pets it wont freeze your game

**Comment by irhrhd** [comment]
Robbins did u check the organization

**Comment by irhrhd** [comment]
I asked u a question
