### ISSUE TITLE
i want everything in the i want 900000000 everything

### ISSUE THREAD

**Issue by hiimjefff** [CRobbins0867/ProdigyHacking--MobileHacking#24]
***What items should be in the account?***:

***What level do you want, how much gold, dark tower floor, etc?***:

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:

**Comment by CRobbins0867** [comment]
okay you have to FILL OUT THE FORM not the title

**Comment by CRobbins0867** [comment]
@hiimjefff im done with the account do you want it?

**Comment by hiimjefff** [comment]
Yes
