### ISSUE TITLE
Put what you want on it I will make a new acc

### ISSUE THREAD

**Issue by savage8685** [CRobbins0867/ProdigyHacking--MobileHacking#4]

**Comment by CRobbins0867** [comment]
do you want epics and everything in your backpack?

**Comment by savage8685** [comment]
Yes

**Comment by savage8685** [comment]
Did you do it

**Comment by savage8685** [comment]
![C6A2A2AD-0796-4998-9DA2-F9340F0EE469](https://user-images.githubusercontent.com/78565536/108003981-0e553f00-6fba-11eb-8094-ad15e8d29a47.png)

**Comment by savage8685** [comment]
There it is

**Comment by savage8685** [comment]
My email is s14936@hindsschools.com

**Comment by CRobbins0867** [comment]
@savage8685  

user: Fortnite_is_AWESOMEE

pass: a12345

**Comment by CRobbins0867** [comment]
sorry it took so long

**Comment by savage8685** [comment]
So can I log in know

**Comment by CRobbins0867** [comment]
yeah

**Comment by CRobbins0867** [comment]
with the info i gave you
