### ISSUE TITLE
Nate8008 account request

### ISSUE THREAD

**Issue by nate8008** [CRobbins0867/ProdigyHacking--MobileHacking#5]
***What items should be in the account?***: all of mira’s gear and every wand

***What level do you want, how much gold, dark tower floor, etc?***: the highest level possible with 500,000 gold max dark tower and member of possible that is all thank you

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***: 
NSC.390@gmail.com

**Comment by CRobbins0867** [comment]
umm so i cant give you membership but i can give you everyhting else you want. is that okay?

**Comment by nate8008** [comment]
I did not see example template but also 2 of each epic, yes that is perfectly fine thanks

**Comment by CRobbins0867** [comment]
okay

**Comment by CRobbins0867** [comment]
done i emailed you the account info

**Comment by nate8008** [comment]
Is there any possible way to add stuff to an account? if not it’s fine.

**Comment by nate8008** [comment]
Is there any way to add something to the account? If not it’s fine.
