### ISSUE TITLE
meh request

### ISSUE THREAD

**Issue by HiWhoIsMe** [CRobbins0867/ProdigyHacking--MobileHacking#6]
***What items should be in the account?***: every outfit, hats, boots, relics, EVERYTHING!!!! 

***What level do you want, how much gold, dark tower floor, etc?***: gold , like, 9999999999999999999, or dark tower lvl, like lvl 133333133333333333, and like yea

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***: cz chelseazhang@gmail.com (note that I am giving this to a friend as a b'day present

**Comment by CRobbins0867** [comment]
@HiWhoIsMe  the info is in your email!
