### ISSUE TITLE
My request

### ISSUE THREAD

**Issue by mynameisherebutblank** [CRobbins0867/ProdigyHacking--MobileHacking#7]
***What items should be in the account?***: All armor, all furniture, treetop terrace house, wands, max items and everything basically in my backpack

***What level do you want, how much gold, dark tower floor, etc?***: lvl 999 or highest possible, max gold, max stats, dark tower floor 100, also 2 of each epic, and all pets if possible

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:
Mynameisherebutblank@gmail.com
Thanks

**Comment by CRobbins0867** [comment]
@mynameisherebutblank  i emailed you the account info!
