### ISSUE TITLE
My request ( thank you )

### ISSUE THREAD

**Issue by PrinceHughJass** [CRobbins0867/ProdigyHacking--MobileHacking#9]
***What items should be in the account?***:All MEMBER furniture, armor, all morph marbles (exceptions):( All Morph Marbles, Resist potions, Miras gear, trialmasters gear, and limited edition items.) Stephen W12-4RD name if possible. Cool Cave house.

***What level do you want, how much gold, dark tower floor, etc?***: lvl 100, one shot everything, 5 billion gold or max, Same for all currencies. 2 Magmischief 2 Shivertusk, 2 Terrosaur, 2 Embershed, 2 applepot, and 2 Smoldash, 1 Big Hex and all member pets, 1 Luma. 

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:
PrinceHughJass@gmail.com
( I was referred by Mynameisherebutblank@gmail.com )

**Comment by CRobbins0867** [comment]
okay got it!

**Comment by CRobbins0867** [comment]
will email you the info rn!

**Comment by CRobbins0867** [comment]
btw are you good at answering questions for people if so are you interested in being a mod

**Comment by PrinceHughJass** [comment]
Sounds good!!

**Comment by PrinceHughJass** [comment]
If you are serious about mod I would be proud, I am new to gimlet though so
I may not be the best

**Comment by CRobbins0867** [comment]
yes i'm not joking about you being a mod but first can i email you a few questions before i promote you when i email you the info details, is that okay?

**Comment by PrinceHughJass** [comment]
Yessir sounds good also I am not going to be online a lot this week as I
live in Texas with constant power outages

**Comment by CRobbins0867** [comment]
sure thats fine

**Comment by CRobbins0867** [comment]
done, just respond back with the questions the best you can
